name: Check Blog Posts

on:
  schedule:
    # Run twice a day at 9 AM and 9 PM UTC
    - cron: '0 9,21 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-blogs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml
    
    - name: Check for new posts
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python check_once.py
    
    - name: Upload state file
      uses: actions/upload-artifact@v3
      with:
        name: bot-state
        path: bot_state.json
        retention-days: 7
    
    - name: Download previous state
      uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        name: bot-state
